CREATE DATABASE SISTEMASAUDE;

USE SISTEMASAUDE;

CREATE TABLE PESSOA (
PES_INT_ID INT IDENTITY(1,1),
PES_STR_NOME VARCHAR (100) NOT NULL,
PES_DATE_DATANASC DATE NOT NULL,
PES_STR_SEXO CHAR (1) NOT NULL,
PES_STR_CPF CHAR (11) NOT NULL,
CONSTRAINT PK_ID_PESSOA PRIMARY KEY (PES_INT_ID),
CONSTRAINT UK_CPF_PESSOA UNIQUE(PES_STR_CPF)
);


CREATE TABLE PACIENTE (
PAC_INT_ID INT IDENTITY(1,1),
PAC_DATE_DATAREGISTRO DATE NOT NULL,
PAC_STR_CONVENIO VARCHAR (100) NOT NULL,
PAC_STR_COMORBIDADE VARCHAR (100) NOT NULL,
PAC_STR_ALERGIA VARCHAR (100) NOT NULL,
CONSTRAINT PK_PAC_ID PRIMARY KEY (PAC_INT_ID)
);

ALTER TABLE PACIENTE
ADD PES_INT_ID INT;

ALTER TABLE PACIENTE
ADD CONSTRAINT UK_PACIENTE_PES_INT_ID UNIQUE (PES_INT_ID);

ALTER TABLE PACIENTE
ADD CONSTRAINT FK_PACIENTE_PESSOA FOREIGN KEY (PES_INT_ID) REFERENCES PESSOA(PES_INT_ID);


CREATE TABLE DOUTOR (
DOU_INT_ID INT IDENTITY (1,1),
DOU_STR_CRM CHAR (8) NOT NULL,
DOU_STR_ESPECIALIDADE VARCHAR (100) NOT NULL,
DOU_STR_HOSPITAIS VARCHAR (100) NOT NULL,
CONSTRAINT UK_DOUTOR_CRM UNIQUE (DOU_STR_CRM)
);

ALTER TABLE DOUTOR
ADD CONSTRAINT PK_DOU_ID PRIMARY KEY (DOU_INT_ID);

ALTER TABLE DOUTOR
ADD PES_INT_ID INT;

ALTER TABLE DOUTOR
ADD CONSTRAINT UK_DOUTOR_PES_INT_ID UNIQUE (PES_INT_ID);

ALTER TABLE DOUTOR
ADD CONSTRAINT FK_DOUTOR_PESSOA FOREIGN KEY (PES_INT_ID) REFERENCES PESSOA(PES_INT_ID);



CREATE TABLE CONSULTA (
CON_INT_ID INT IDENTITY (1,1),
CON_DATEH_DATAHORA DATETIME NOT NULL,
CON_STR_SINTOMAS VARCHAR (200) NOT NULL,
CON_STR_DIAGNOSTICO VARCHAR (200) NOT NULL,
CON_STR_OBSERVAÇÕES VARCHAR (200) NOT NULL,
PAC_INT_ID INT,
DOU_INT_ID INT,
CONSTRAINT FK_CONSULTA_PACIENTE FOREIGN KEY (PAC_INT_ID) REFERENCES PACIENTE (PAC_INT_ID),
CONSTRAINT FK_CONSULTA_DOUTOR FOREIGN KEY (DOU_INT_ID) REFERENCES DOUTOR (DOU_INT_ID)
);

ALTER TABLE CONSULTA
ADD CONSTRAINT PK_CON_ID PRIMARY KEY (CON_INT_ID)

CREATE TABLE RECEITA (
REC_INT_ID INT IDENTITY (1,1),
REC_STR_POSOLOGIA VARCHAR (200) NOT NULL,
REC_DATE_DATA DATE NOT NULL,
REC_DATE_VALIDADE DATE NOT NULL,
REC_STR_OBSERVAÇÕES VARCHAR (200) NOT NULL,
CON_INT_ID INT,
CONSTRAINT PK_REC_ID PRIMARY KEY (REC_INT_ID),
CONSTRAINT UK_RECEITA_CON_INT_ID UNIQUE (CON_INT_ID),
CONSTRAINT FK_RECEITA_CONSULTA FOREIGN KEY (CON_INT_ID) REFERENCES CONSULTA(CON_INT_ID)
);

CREATE TABLE RECEITA_MEDICAMENTO (
REC_INT_ID INT,
MED_INT_ID INT,
CONSTRAINT PK_CONSULTA_MEDICAMENTO PRIMARY KEY (REC_INT_ID, MED_INT_ID),
CONSTRAINT FK_RECEITA FOREIGN KEY (REC_INT_ID) REFERENCES RECEITA(REC_INT_ID),
CONSTRAINT FK_MEDICAMENTO FOREIGN KEY (MED_INT_ID) REFERENCES MEDICAMENTO(MED_INT_ID)
);

CREATE TABLE MEDICAMENTO (
MED_INT_ID INT IDENTITY (1,1),
MED_STR_NOME VARCHAR (200) NOT NULL,
MED_STR_PRINCATIVO VARCHAR (200) NOT NULL,
MED_DOU_DOSAGEM FLOAT NOT NULL,
MED_DOU_PRECO FLOAT NOT NULL,
MED_STR_FABRICANTE VARCHAR (200) NOT NULL
CONSTRAINT PK_MED_ID PRIMARY KEY (MED_INT_ID)
);
